### PR TITLE
add sleep with exponential backoff to EIB scraper

### LINKED ISSUE #57: EIB Scraper Broken
Wondering if someone could take a look at this -😩... Thanks 

Appears broken for any search term 

image

### PR DESCRIPTION
**Pull request by justalfred**
fixes #57 . I think the site did change. But, only in that it's way slower. I added in a loop to wait for up to about a minute. Anyone else want to test this? @jimjshields @mdgis @JohnWinter

### CODE REVIEW

**Comment by justalfred** [comment]
Also, I noticed the originally search string searched until 2018. Not good for next year, so I took it out. Now I'm seeing that another commit somewhere broke the download function, so I'm tracking that now.

**Comment by justalfred** [comment]
OK, it wasn't too bad. It turns out Pathlib only returns the tail end of a path with `path_obj.name`, so I had to use `path_obj.resolve()` to get the full path. I think it's good now. @xtream1101 you might find this interesting. It's weird that Pathlib wouldn't offer `path_obj.full_name` or something similar....

**Comment by justalfred** [comment]
Well, weirdly, this worked on my ubuntu machine, but failed on OSX. And now I think it's weird that my last fix worked for me, since I butchered the filename used by the download route. But now, I think it should work for everyone. @mdgis would you like to test?

**Comment by mdgis** [comment]
Cool - ok EIB works for me a again - Thanks

**Comment by justalfred** [comment]
Oh, we never merged this. I'll merge it in, then.

**Pull request merged**
