### PR TITLE
Added kfw scraper

### PR DESCRIPTION
**Pull request by xtream1101**
Returns the results as seen when searching

### CODE REVIEW

**Comment by justalfred** [comment]
dang, thanks for this, but I already got Adriano and Victor's version merged.

**Comment by justalfred** [comment]
Yeah, I had that inclination, too, but when I checked with them, they said that in practice, the site's search function wasn't very good, and they were able to get more relevant hits with their approach. They passed it by Dustin, and since it returned a small number of results that would otherwise have been missed, he was happy with it.

That said, I suppose the opposite is possible, too, so I wonder if we can combine the results of both approaches. @xtream1101 @jimjshields What do you think?

**Comment by jimjshields** [comment]
I think combining both works, and we should indicate the difference by the "DFI" column (e.g., have "KfW Search" and "KfW API" or something like that) — would also be good to have a backup if one breaks for whatever reason.

**Comment by xtream1101** [comment]
I think returning results for both can't hurt. I like @jimjshields idea with giving them different DFI names so the user can still tell them apart.

**Comment by justalfred** [comment]
Closing. This is now incorporated in #44.

**Pull request closed without merging**
